version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:10.0.3-ubuntu
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    networks:
      - nlb_ingress
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  nlb_ingress:
    external: true

volumes:
  grafana_data:
    external: true
